---
  title: "Pandemic Indicators Fetcher"
---
  
  Set up libraries
```{r Setup, message=FALSE, warning=FALSE}
# Setup
library("cansim")
library("dplyr")

```

Download cansim vectors
```{r Setup}
v2057793<-get_cansim_vector("v2057793",start_time = as.Date("2000-01-01"))
v2057793<-v2057793 %>% select("REF_DATE","VALUE") %>% rename("BC Employment, total" = "VALUE")
v2064705<-get_cansim_vector("v2064705",start_time = as.Date("2000-01-01"))
v2064705<-v2064705 %>% select("REF_DATE","VALUE")  %>% rename("BC Unemployment Rate" = "VALUE")
v2064710<-get_cansim_vector("v2064710",start_time = as.Date("2000-01-01"))
v2064710<-v2064710 %>% select("REF_DATE","VALUE")  %>% rename("BC Employment, Males" = "VALUE")
v2064714<-get_cansim_vector("v2064714",start_time = as.Date("2000-01-01"))
v2064714<-v2064714 %>% select("REF_DATE","VALUE")  %>% rename("BC Unemployment Rate, Males" = "VALUE")
v2064719<-get_cansim_vector("v2064719",start_time = as.Date("2000-01-01"))
v2064719<-v2064719 %>% select("REF_DATE","VALUE")  %>% rename("BC Employment, Females" = "VALUE")
v2064723<-get_cansim_vector("v2064723",start_time = as.Date("2000-01-01"))
v2064723<-v2064723 %>% select("REF_DATE","VALUE")  %>% rename("BC Unemployment Rate, Females" = "VALUE")
v2064706<-get_cansim_vector("v2064706",start_time = as.Date("2000-01-01"))
v2064706<-v2064706 %>% select("REF_DATE","VALUE")  %>% rename("BC Participation Rate" = "VALUE")
v2064715<-get_cansim_vector("v2064715",start_time = as.Date("2000-01-01"))
v2064715<-v2064715 %>% select("REF_DATE","VALUE")  %>% rename("BC Participation Rate, Males" = "VALUE")
v2064724<-get_cansim_vector("v2064724",start_time = as.Date("2000-01-01"))
v2064724<-v2064724 %>% select("REF_DATE","VALUE")  %>% rename("BC Participation Rate, Females" = "VALUE")
v1593420<-get_cansim_vector("v1593420",start_time = as.Date("2000-01-01"))
v1593420<-v1593420 %>% select("REF_DATE","VALUE")  %>% rename("BC Average Hourly Earnings, including OT, Hrly Workers" = "VALUE")
v2166779<-get_cansim_vector("v2166779",start_time = as.Date("2000-01-01"))
v2166779<-v2166779 %>% select("REF_DATE","VALUE")  %>% rename("BC Avg Hrly Wage Rate, Employees 15 yrs+" = "VALUE")

v2064705<-get_cansim_vector("v2064705",start_time = as.Date("2000-01-01"))
v2064705<-v2064705 %>% select("REF_DATE","VALUE")  %>% rename("BC Unemployment Rate" = "VALUE")

v2064705<-get_cansim_vector("v2064705",start_time = as.Date("2000-01-01"))
v2064705<-v2064705 %>% select("REF_DATE","VALUE")  %>% rename("BC Unemployment Rate" = "VALUE")

v2064705<-get_cansim_vector("v2064705",start_time = as.Date("2000-01-01"))
v2064705<-v2064705 %>% select("REF_DATE","VALUE")  %>% rename("BC Unemployment Rate" = "VALUE")

v2064705<-get_cansim_vector("v2064705",start_time = as.Date("2000-01-01"))
v2064705<-v2064705 %>% select("REF_DATE","VALUE")  %>% rename("BC Unemployment Rate" = "VALUE")

v2064705<-get_cansim_vector("v2064705",start_time = as.Date("2000-01-01"))
v2064705<-v2064705 %>% select("REF_DATE","VALUE")  %>% rename("BC Unemployment Rate" = "VALUE")

v2064705<-get_cansim_vector("v2064705",start_time = as.Date("2000-01-01"))
v2064705<-v2064705 %>% select("REF_DATE","VALUE")  %>% rename("BC Unemployment Rate" = "VALUE")

v2064705<-get_cansim_vector("v2064705",start_time = as.Date("2000-01-01"))
v2064705<-v2064705 %>% select("REF_DATE","VALUE")  %>% rename("BC Unemployment Rate" = "VALUE")

OUTPUT<-bind_cols(c(v2057793,v2064705[2],v2064710[2],v2064714[2],v2064719[2],v2064723[2],v2064706[2],v2064715[2],v2064724[2],v1593420[2],v2166779[2]))


```
